framework:
    workflows:
        book:
            marking_store:
                type: single_state
            supports:
                - AppBundle\Entity\Book
            places:
                - free
                - reserved
                - taken
            transitions:
                reserve:
                    from: free
                    to: reserved
                take_without_reserve:
                    from: free
                    to: taken
                decline_reserve:
                    from: reserved
                    to: free
                take:
                    from: reserved
                    to: taken
                drop:
                    from: taken
                    to: free